packages:
  - apps/*
  - packages/*

allowBuilds:
  "@livekit/local-inference": false
  esbuild: true
  protobufjs: false
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - globals@17.8.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
