packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - globals@17.8.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - workerd
